### ISSUE TITLE
Options window without displaying settings

### ISSUE THREAD

**Issue by UnlimitedChild** [horsicq/nfdx64dbg#2]
https://github.com/ThunderCls/x64dbg_acid_lime_theme/issues/1

**Comment by horsicq** [comment]
Thanks a lot for the bugreport. I'll take a look.

**Comment by horsicq** [comment]
I'll fix it in the new version of the plugin. If you cannot wait you could make a fix patch for this issue:

Rename folder "**icons**" to "**icons_fix**"

Replace strings in style.css:

"**./icons**" to "**./icons_fix**"

**Comment by UnlimitedChild** [comment]
> I'll fix it in the new version of the plugin. If you cannot wait you could make a fix patch for this issue:
> 
> Rename folder "**icons**" to "**icons_fix**"
> 
> Replace strings in style.css:
> 
> "**./icons**" to "**./icons_fix**"

This fix, as I found out, does not work ...

**Comment by horsicq** [comment]
Thanks a lot for the test. I created a new version of Plugin https://github.com/horsicq/nfdx64dbg/releases/tag/0.09

I guess it should work :)

**Comment by UnlimitedChild** [comment]
> I guess it should work :)

does not work, as soon as the plugin is deleted, everything works ..

**Comment by horsicq** [comment]
Hmm. 
I got the last version of x64dbg (snapshot_2019-07-02_16-06 https://x64dbg.com). 
The last version of x64dbg_acid_lime_theme(https://github.com/ThunderCls/x64dbg_acid_lime_theme)
The last version of nfdx64dbg(https://github.com/horsicq/nfdx64dbg/releases/tag/0.09)

Options window displays settings.

Here is the bundle: 
https://www.dropbox.com/s/xkj363xuvfds259/x64dbg_nfd.zip?dl=1

**Comment by UnlimitedChild** [comment]
This is only a graphic theme, for completeness, you need to add a style (replace debugger configuration). If you connect your other plugins, the effect is repeated.

Your archive with the changes can be downloaded below ..
https://www.solidfiles.com/v/r6Xa3gv5AxAYv

And this is the style that needs to be renamed to x64dbg.ini or x32dbg.ini
[6fffbe7f3e2edd697b36a2decab80b64-d2695424ba70771f27a16fd34239d4867460d3e5.zip](https://github.com/horsicq/nfdx64dbg/files/3410168/6fffbe7f3e2edd697b36a2decab80b64-d2695424ba70771f27a16fd34239d4867460d3e5.zip)

**Comment by horsicq** [comment]
Thanks a lot for the test and the bundle!

I think Stringsx64dbg plugin has been already fixed. I made a new version yesterday: https://github.com/horsicq/stringsx64dbg/releases/tag/0.04

Peviewer plugin still has this bug. I'll fix it soon.

**Comment by robertsi** [comment]
Seems this is still not fixed. https://github.com/x64dbg/x64dbg/issues/2229
Theme https://github.com/ThunderCls/x64dbg_vs_dark

**Comment by horsicq** [comment]
Ok. Thanks a lot for the bugreport.
